# Generated by Django 4.2.7 on 2025-11-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='NewsCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('news_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
            options={
                'db_table': 'news_clusters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source_types',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.ForeignKey(db_column='source_type_id', on_delete=django.db.models.deletion.CASCADE, to='news.sourcetype')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='RawNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_img', models.TextField(blank=True, null=True)),
                ('content_video', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='news.language')),
                ('source', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, to='news.source')),
            ],
            options={
                'db_table': 'raw_news',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(db_column='cluster_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='news.newscluster')),
                ('news', models.ForeignKey(db_column='news_id', on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='news.rawnews')),
            ],
            options={
                'db_table': 'news_cluster_members',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=50)),
                ('source_news_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.OneToOneField(db_column='cluster_id', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='news.newscluster')),
            ],
            options={
                'db_table': 'generated_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rawnews',
            index=models.Index(fields=['published_at'], name='raw_news_publish_1a62ee_idx'),
        ),
        migrations.AddIndex(
            model_name='rawnews',
            index=models.Index(fields=['source', 'published_at'], name='raw_news_source__420e34_idx'),
        ),
        migrations.AddIndex(
            model_name='rawnews',
            index=models.Index(fields=['category', 'published_at'], name='raw_news_categor_3c8c33_idx'),
        ),
        migrations.AddIndex(
            model_name='newsclustermember',
            index=models.Index(fields=['cluster'], name='news_cluste_cluster_0cc812_idx'),
        ),
        migrations.AddIndex(
            model_name='newsclustermember',
            index=models.Index(fields=['news'], name='news_cluste_news_id_c1f68b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsclustermember',
            unique_together={('cluster', 'news')},
        ),
        migrations.AddIndex(
            model_name='newscluster',
            index=models.Index(fields=['category', 'created_at'], name='news_cluste_categor_12d7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='newscluster',
            index=models.Index(fields=['updated_at'], name='news_cluste_updated_22697a_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status', 'created_at'], name='generated_r_status_dde2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['published_at'], name='generated_r_publish_5393d5_idx'),
        ),
    ]
